create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role text not null default 'student' check (role in ('student', 'instructor')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles read authenticated" on public.profiles;
drop policy if exists "profiles insert own student" on public.profiles;

create policy "profiles read authenticated"
  on public.profiles
  for select
  to authenticated
  using (true);

create policy "profiles insert own student"
  on public.profiles
  for insert
  to authenticated
  with check (id = auth.uid() and role = 'student');

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'display_name', new.email),
    'student'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create table if not exists public.instructor_invites (
  id bigint generated by default as identity primary key,
  label text,
  code_hash text not null,
  used_by uuid references auth.users(id) on delete set null,
  used_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.instructor_invites enable row level security;

create table if not exists public.drone_app_state (
  id text primary key,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.drone_app_state enable row level security;

drop policy if exists "drone app state read" on public.drone_app_state;
drop policy if exists "drone app state insert" on public.drone_app_state;
drop policy if exists "drone app state update" on public.drone_app_state;
drop policy if exists "drone app state read authenticated" on public.drone_app_state;

create policy "drone app state read authenticated"
  on public.drone_app_state
  for select
  to authenticated
  using (true);

create or replace function public.redeem_instructor_invite(invite_code text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  invite_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select id into invite_id
  from public.instructor_invites
  where used_at is null
    and (expires_at is null or expires_at > now())
    and code_hash = crypt(invite_code, code_hash)
  order by created_at
  limit 1
  for update;

  if invite_id is null then
    return false;
  end if;

  update public.profiles
  set role = 'instructor'
  where id = auth.uid();

  update public.instructor_invites
  set used_by = auth.uid(),
      used_at = now()
  where id = invite_id;

  return true;
end;
$$;

create or replace function public.save_drone_app_state(state_id text, new_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  caller uuid := auth.uid();
  caller_role text;
  current_data jsonb;
  caller_student jsonb;
  students jsonb;
  student_index int;
begin
  if caller is null then
    raise exception 'Not authenticated';
  end if;

  select role into caller_role
  from public.profiles
  where id = caller;

  if caller_role = 'instructor' then
    insert into public.drone_app_state (id, data, updated_at)
    values (state_id, new_data, now())
    on conflict (id) do update
      set data = excluded.data,
          updated_at = now();
    return new_data;
  end if;

  select data into current_data
  from public.drone_app_state
  where id = state_id
  for update;

  if current_data is null then
    current_data := jsonb_build_object('students', '[]'::jsonb, 'instructors', '[]'::jsonb);
  end if;

  select value into caller_student
  from jsonb_array_elements(coalesce(new_data->'students', '[]'::jsonb)) as student(value)
  where value->>'id' = caller::text
  limit 1;

  if caller_student is null then
    raise exception 'Student record missing';
  end if;

  students := coalesce(current_data->'students', '[]'::jsonb);

  select ordinality::int - 1 into student_index
  from jsonb_array_elements(students) with ordinality as student(value, ordinality)
  where value->>'id' = caller::text
  limit 1;

  if student_index is null then
    students := students || jsonb_build_array(caller_student);
  else
    students := jsonb_set(students, array[student_index::text], caller_student, true);
  end if;

  current_data := jsonb_set(current_data, '{students}', students, true);

  insert into public.drone_app_state (id, data, updated_at)
  values (state_id, current_data, now())
  on conflict (id) do update
    set data = excluded.data,
        updated_at = now();

  return current_data;
end;
$$;

grant execute on function public.redeem_instructor_invite(text) to authenticated;
grant execute on function public.save_drone_app_state(text, jsonb) to authenticated;

-- Lag en instruktør-invitasjon med en kode du velger:
-- insert into public.instructor_invites (label, code_hash)
-- values ('Instruktørkode Daniel', crypt('SKRIV-DIN-KODE-HER', gen_salt('bf')));
